Fix example on README
This commit fixes 2 erros I had when running the example on README:
- `TypeError: from_pretarined() got an unexpected keyword argument 'variant'`
- `RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`